import type { AppDatabase } from './types';

export const DEFAULT_DATABASE: AppDatabase = {
  categories: [
    { id: 'oriental', name: 'الشرقي' },
    { id: 'nabulsia', name: 'قسم النابلسية' },
    { id: 'dairy', name: 'قسم الألبان' },
    { id: 'jordanian', name: 'القسم الأردني' },
    { id: 'western', name: 'الحلويات الغربية' },
    { id: 'offers', name: 'عروض خاصة' },
    { id: 'drinks', name: 'المشروبات' },
  ],
  settings: {
    whatsapp: '201023728183',
    ticker: 'عرض خاص: خصم 10% على جميع الحلويات الشرقية عند الطلب عبر الموقع! | التوصيل مجاني للطلبات فوق 500 ج.م | جرب الكنافة النابلسية الآن!',
    isRamadanMode: false,
    homeBackground: '',
  },
  stats: { totalOrders: 0, totalRevenue: 0 },
  vouchers: { OUDELLE10: 0.10, WELCOME: 0.05, OFF50: 0.50, OUDELLE2026: 0.10 },
  delivery: [
    { name: 'نجع حمادي', price: 30 },
    { name: 'خارج نجع حمادي', price: 40 },
    { name: 'هو', price: 50 },
    { name: 'مدينه الالمونيوم', price: 60 },
    { name: 'قريه بركه', price: 70 },
  ],
  gallery: [],
  orders: [],
  updates: [],
  uploadedImages: {},
  oriental: [
    { name: 'بسبوسه ساده', price: 175, type: 'kg', img: 'بسبوسه ساده.jpg' },
    { name: 'بسبوسه مكسرات', price: 240, type: 'kg', img: 'بسبوسه مكسرات.jpg' },
    { name: 'بسبوسه قشطه', price: 220, type: 'kg', img: 'بسبوسه قشطه.jpg' },
    { name: 'بسبوسه نوتيلا', price: 215, type: 'kg', img: 'بسبوسه نوتيلا.jpg' },
    { name: 'بسبوسه لوتس', price: 215, type: 'kg', img: 'بسبوسه لوتس.jpg' },
    { name: 'جلاش ساده', price: 170, type: 'kg', img: 'جلاش ساده.jpg' },
    { name: 'جلاش كريمه', price: 200, type: 'kg', img: 'جلاش كريمه.jpg' },
    { name: 'جلاش برم', price: 230, type: 'kg', img: 'جلاش برم.jpg' },
    { name: 'بقلاوه تركي', price: 400, type: 'kg', img: 'بقلاوه تركي.jpg' },
    { name: 'بقلاوه تركي فستق حلبي', price: 650, type: 'kg', img: 'بقلاوه تركي فسدق.jpg' },
    { name: 'بقلاوه قشطه', price: 650, type: 'kg', img: 'بقلاوه قشطه.jpg' },
    { name: 'شكلمه سمن بلدي', price: 280, type: 'kg', img: 'شكلامه سمنه بلدي.jpg' },
    { name: 'مدلعه سمن بلدي', price: 220, type: 'kg', img: 'مدلعه سمنه.jpg' },
    { name: 'حبيبه مكسرات', price: 220, type: 'kg', img: 'حبيبه مكسرات.jpg' },
    { name: 'رموش الست', price: 220, type: 'kg', img: 'رموش الست.jpg' },
    { isMix: true, title: 'علي كيفك (شرقي مشكل)', source: 'oriental', name: 'مشكل شرقي', price: 0, type: 'kg', img: '' },
  ],
  nabulsia: [
    { name: 'كنافه نابلسيه جبنه', price: 35, type: 'piece', img: 'كنافه نبلسيه.jpg.png' },
    { name: 'كنافه نابلسيه جبنه (وسط)', price: 50, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه جبنه (كبيرة)', price: 120, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه جبنه (عائلية)', price: 200, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه جبنة (جامبو)', price: 250, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه قشطه', price: 35, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه قشطه (وسط)', price: 50, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه قشطه (كبيرة)', price: 120, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه قشطه (عائلية)', price: 200, type: 'piece', img: '' },
    { name: 'كنافه نابلسيه قشطه (جامبو)', price: 250, type: 'piece', img: '' },
  ],
  dairy: [
    { name: 'رز بلبن ساده', price: 25, type: 'piece', img: '' },
    { name: 'قشطوطه (لوتس/نوتيلا/بستاشيو)', price: 75, type: 'piece', img: '' },
    { name: 'ترلتشي (كراميل/شوكلت)', price: 75, type: 'piece', img: '' },
    { name: 'محلايه شاميه', price: 75, type: 'piece', img: '' },
    { name: 'ام علي مكسرات', price: 75, type: 'piece', img: '' },
    { name: 'طاجن نوتيلا', price: 75, type: 'piece', img: '' },
    { name: 'مولتن كيك', price: 55, type: 'piece', img: '' },
    { name: 'شوكلت بول', price: 55, type: 'piece', img: '' },
  ],
  jordanian: [
    { name: 'برازق سمسم', price: 30, type: 'piece', img: '' },
    { name: 'معمول بالتمر', price: 300, type: 'piece', img: '' },
    { name: 'غريبه', price: 300, type: 'piece', img: '' },
    { name: 'معمول سميط عين جمل', price: 300, type: 'piece', img: '' },
    { name: 'ليالي لبنان', price: 175, type: 'kg', img: '' },
    { name: 'حبيبه', price: 175, type: 'kg', img: '' },
    { name: 'وربات', price: 175, type: 'kg', img: '' },
    { name: 'نموره', price: 175, type: 'kg', img: '' },
    { name: 'عيش السرايا', price: 175, type: 'kg', img: '' },
    { name: 'دحدح', price: 175, type: 'kg', img: '' },
    { name: 'هريسه', price: 175, type: 'kg', img: '' },
  ],
  western: [
    { name: 'تورته مقاس 18', price: 200, type: 'piece', img: '' },
    { name: 'تورته مقاس 20', price: 250, type: 'piece', img: '' },
    { name: 'تورته مقاس 22', price: 300, type: 'piece', img: '' },
    { name: 'تورته مقاس 24', price: 350, type: 'piece', img: '' },
    { name: 'تورته مقاس 26', price: 400, type: 'piece', img: '' },
    { name: 'تورته مقاس 28', price: 450, type: 'piece', img: '' },
    { name: 'تشيز كيك', price: 45, type: 'piece', img: '' },
    { name: 'تشيز كيك اسباني', price: 80, type: 'piece', img: '' },
    { name: 'فادج', price: 55, type: 'piece', img: '' },
    { name: 'مولتن كيك', price: 55, type: 'piece', img: '' },
    { name: 'دونتس', price: 40, type: 'piece', img: '' },
    { name: 'سويس رول', price: 100, type: 'piece', img: '' },
    { name: 'دسبسيتو كبير', price: 60, type: 'piece', img: '' },
    { name: 'دسبسيتو صغير', price: 40, type: 'piece', img: '' },
    { name: 'انجلش كيك', price: 175, type: 'piece', img: '' },
    { name: 'بفترول', price: 75, type: 'piece', img: '' },
    { name: 'سينبون', price: 45, type: 'piece', img: '' },
    { name: 'تارت', price: 48, type: 'piece', img: '' },
    { name: 'اكلير', price: 45, type: 'piece', img: '' },
    { name: 'جاتو كلاسيك', price: 25, type: 'piece', img: '' },
  ],
  offers: [
    { name: 'عرض 1', price: 100, type: 'piece', img: '' },
    { name: 'عرض 2', price: 200, type: 'piece', img: '' },
  ],
  drinks: [
    { name: 'مياه معدنية', price: 10, type: 'piece', img: '' },
    { name: 'شاي كارك صغير', price: 15, type: 'piece', img: '' },
    { name: 'شاي كارك كبير', price: 25, type: 'piece', img: '' },
    { name: 'قهوة تركي', price: 20, type: 'piece', img: '' },
    { name: 'قهوه ساده', price: 20, type: 'piece', img: '' },
  ],
};
